- apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  sudo: true
  with_items:
    - python-pycurl
    - python-psycopg2

- apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc
  sudo: true

- apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main'
  sudo: true

- apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  sudo: true
  with_items:
    - postgresql
    - postgresql-contrib

- postgresql_user: name=postgres password=postgres
  sudo: true
  sudo_user: postgres

- postgresql_db: name={{ database }}
  sudo: true
  sudo_user: postgres

