- local_action:
    module: rds
    command: facts
    instance_name: "{{ rds_instance_name }}"
  register: rds

- set_fact:
    database_url: "postgres://postgres:postgres@{{ rds.instance.endpoint }}/{{ db_name }}"

- include: setup.yml
  sudo: true

- include: deploy.yml
  tags:
    - deploy
  sudo: true
  sudo_user: rails
