defaults: &defaults
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5
  host: localhost

development:
  <<: *defaults
  database: tv_development

test:
  <<: *defaults
  database: tv_test

docker:
  <<: *defaults
  database: tv_docker
  host: db

production:
  <<: *defaults
  database: tv_production
