#!/usr/bin/env ansible-playbook
---

- name: Vagrant single instance deployment

  hosts: all

  vars:
    home: /var/www
    database: tv_production
    project: teamvillage
    revision: master
    clone_url: git@github.com:chuvayva/teamvillage.git
    env:
      rails_env: production

  roles:
    - common
    - db
    - web
