#!/usr/bin/env ansible-playbook

---

- name: << Vagrant common playbook >>
  hosts: all
  vars:
    env:
      RAILS_ENV: production
      DATABASE_URL: "postgres://postgres:postgres@free-tire.ccpiovbexhxm.us-east-1.rds.amazonaws.com:5432/{{ database }}"
  roles:
    - common
    - web

