#!/usr/bin/env ansible-playbook
---

- name: Vagrant single instance deployment
  hosts: all
  vars:
    home_dir: /vagrant
    database: tv_production
    rails_env: production
    rails_command_env:
      RAILS_ENV: production
    project: teamvillage
  tasks:
    - template: src=templates/bash_profile.j2 dest=~/.bash_profile

    - apt_repository: repo={{ item }}
      sudo: yes
      with_items:
        - "ppa:chris-lea/node.js"
        - "ppa:brightbox/ruby-ng"

    - name: install apt packages
      apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
      sudo: yes
      with_items:
        - git-core
        - curl
        - zlib1g-dev
        - build-essential
        - libssl-dev
        - libreadline-dev
        - libyaml-dev
        - libsqlite3-dev
        - libxml2-dev
        - libxslt1-dev
        - libcurl4-openssl-dev
        - python-software-properties
        - libffi-dev

        # for app
        - ruby2.0
        - nodejs
        - nginx
        # for bundle
        - make
        - ruby2.0-dev
        - libpq-dev
        - g++

    - file: src=/usr/bin/{{ item }}2.0 dest=/usr/bin/{{ item }} state=link
      with_items: [ruby, gem, irb]
      sudo: yes

    - gem: name=bundler state=present user_install=no
      sudo: yes

    - command: bundle --deployment --without="test development" chdir={{ home_dir }}
      environment: rails_command_env
      register: result
      changed_when: "'Installing' in result.stdout"

    # pg
    - apt: pkg={{ item }}
      sudo: yes
      with_items: [python-pycurl, python-psycopg2]
    - apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc
      sudo: yes
    - apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main'
      sudo: yes
    - apt: pkg={{item}}
      sudo: yes
      with_items:
        - postgresql
        - postgresql-contrib

    - postgresql_user: name=postgres password=postgres
      sudo: yes
      sudo_user: postgres

    - postgresql_db: name={{ database }}
      sudo: yes
      sudo_user: postgres



    - name: Db migration
      command: ./bin/rake db:migrate chdir={{ home_dir }}
      environment: rails_command_env
      register: result
      changed_when: result.stdout != ''

    - name: Assets precompile
      command: ./bin/rake assets:precompile chdir={{ home_dir }}
      environment: rails_command_env
      register: result
      changed_when: result.stderr != ''

    - template: src=templates/etc_init.d_unicorn.j2 dest=/etc/init.d/unicorn-{{ project }} owner=root group=root mode=0755
      sudo: yes
      notify: restart unicorn

    - file: path=/tmp/sockets state=directory owner=vagrant group=vagrant

    - file: path={{ home_dir }}/{{ item }} state=directory owner=vagrant group=vagrant
      with_items:
        - shared/pids
        - shared/sockets
        - shared/log

    - template: src=templates/etc_nginx_unicorn.j2 dest=/etc/nginx/sites-available/default
      sudo: yes
      notify: reload nginx


    - shell: echo "deployed!"
      changed_when: false

  handlers:
    - name: restart unicorn
      service: name=unicorn-{{ project }} state=restarted
      sudo: yes

    - name: reload nginx
      service: name=nginx state=reloaded
      sudo: yes

